server:
  port: 8082

spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
security:
  jwt:
    public-key: "classpath:rs256-public.pem"

inventory:
  service:
    url: http://localhost:8081
